language: c

before_install:
  - sudo apt-get --quiet update
  - sudo apt-get --quiet --quiet --yes install wget
  - wget --no-directories --no-host-directories --recursive --accept '*.deb' --no-parent 'https://repo.varnish-cache.org/pkg/5.0.0/'
  - sudo dpkg --install *.deb || sudo apt-get --quiet --quiet --yes install --fix-broken

before_script:
  - ./autogen.sh
  - ./configure --prefix=/usr
  - make -j1

script:
  - make check -j1

compiler:
  - clang
  - gcc
